### ISSUE TITLE
robotgo build failure

### ISSUE THREAD

**Issue by 3052** [1fpsvideo/1fps#4]
> go build
# github.com/go-vgo/robotgo
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\img.go:92:40: undefined: Bitmap
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\img.go:107:38: undefined: Bitmap
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\img.go:137:20: undefined: Bitmap
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\screen.go:26:28: undefined: Rect
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:9:2: undefined: Move
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:17:2: undefined: Toggle
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:18:2: undefined: MilliSleep
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:20:2: undefined: MoveSmooth
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:21:2: undefined: Toggle
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:29:9: undefined: MoveSmooth
C:\Users\Steven\go\pkg\mod\github.com\go-vgo\robotgo@v0.110.1\robotgo_fn_v1.go:29:9: too many errors

**Comment by ro31337** [comment]
Yes, it's a well-known Windows-related failure: https://github.com/robotn/gohook/issues/27

Possible solutions: https://github.com/go-vgo/robotgo/issues/588#issuecomment-1665070727 

I'm looking into that, and fix. Meanwhile if somebody else is willing to fix, it is ok as well.

**Comment by 3052** [comment]
> Yes, it's a well-known Windows-related failure

that may be, but its not mentioned anywhere here:

https://github.com/1fpsvideo/1fps

which is especially concerning, since Go is typically a "works everywhere" type of language. so if you are going to violate that, you should advertise loudly on the Readme. additionally, you have this:

> For Mac, Linux, or Windows

https://1fps.video

which is either an outright lie, or just a wish. either way, please do better. dont make people fail to compile your stuff to find out their OS isn't even supported, even though it is advertised as such. would be better to just say "Linux only" until you are sure otherwise.

**Comment by ro31337** [comment]
See updated docs as workaround: https://github.com/1fpsvideo/1fps?tab=readme-ov-file#windows-users

Will copy them here:

## Windows Users

Compiling on Windows requires a few additional steps. Please follow these instructions:

1. Install Golang, for example from https://webinstall.dev/golang/
2. Install the GCC compiler pack from https://github.com/skeeto/w64devkit/releases
   - Download the exe file, which will automatically unpack (probably to your Downloads folder)
   - Run w64devkit.exe
3. In the w64devkit terminal, type:
   ```
   go env -w CGO_ENABLED=1
   ```
4. Run the main command from the 1fps.video website. It's better to copy the command directly from the website or use the latest version from the tags:
   ```
   go run github.com/1fpsvideo/1fps@v0.1.1
   ```

Please note that these steps are necessary until we produce binaries for Windows. We understand that compiling on Windows has been challenging for various software projects. We're currently in alpha, so please check back later for easier installation options with pre-compiled binaries.

**Comment by 3052** [comment]
>     1. Install Golang, for example from https://webinstall.dev/golang/

no need to run a third party script for these, the official website has its own instruction, thats literally one line:

https://go.dev/doc/install

**Comment by ro31337** [comment]
Closing as nothing you can do here. Just use a certain way of building things for Windows. The better option would be to provide binaries, ideally signed. Should be implemented in the future.
